# Generated by Django 3.1.6 on 2021-05-31 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PList', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barangay',
            old_name='barangay',
            new_name='zbarangay',
        ),
    ]
