# Generated by Django 3.1.6 on 2021-06-17 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PList', '0002_auto_20210531_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelerprofile',
            name='age',
        ),
    ]
